# Generated by Django 3.2.18 on 2023-05-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20230507_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=65)),
                ('flight', models.ManyToManyField(blank=True, related_name='passengers', to='flights.Flights')),
            ],
        ),
    ]
